 package AddEmp;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;	
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class EmpList extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    PreparedStatement stat;
    ResultSet rs;
    /** Creates new form EmpList
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException */
    public EmpList() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setVisible(true);
        textArea1.setEditable(false);
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        con=DriverManager.getConnection("jdbc:odbc:Employee");
        stmt=con.createStatement();
        rs=stmt.executeQuery("Select * from emp");
        textArea1.append("Name\t\tAddress\t\t\tPost\t\tEMPID\n");
        while(rs.next())
        {
            textArea1.append(rs.getString(1)+"\t");
            textArea1.append(rs.getString(2)+"\t");
            textArea1.append(rs.getString(3)+"\t");
            textArea1.append(Integer.toString(rs.getInt(10))+"\t");
            textArea1.append("\n");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        textArea1 = new java.awt.TextArea();
        button1 = new java.awt.Button();

        menu1.setLabel("Menu");
        menuBar1.add(menu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setLabel("Back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

private void button1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
// TODO add your handling code here:
    this.setVisible(false);
    Menuscm menu = new Menuscm();
    menu.setVisible(true);
}                                       

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new EmpList().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(EmpList.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Button button1;
    private java.awt.Menu menu1;
    private java.awt.MenuBar menuBar1;
    private java.awt.TextArea textArea1;
    // End of variables declaration                   

}

 
