 package AddEmp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
 import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Menuscm extends javax.swing.JFrame {
        Connection con;
        Statement stmt;
        PreparedStatement stat;
        ResultSet rs;

    /** Creates new form */
    public Menuscm() {
        try {
            initComponents();
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:Employee");
            stmt=con.createStatement();
            rs=stmt.executeQuery("select * from Emp" );
        } catch (SQLException ex) {
            if(ex.getErrorCode()==208)
            {
                try {
                    rs = stmt.executeQuery("CREATE TABLE [dbo].[Emp]([Name] [char](20) NOT NULL,[Address] [char](30) NOT NULL,[Post] [char](10) NOT NULL,[Experiance] [int] NULL,[Salary] [int] NOT NULL,[HRA] [int] NULL,[TA] [int] NULL,[PF] [int] NULL,[ITax] [int] NULL,[Eid] [int] NOT NULL) ON [PRIMARY]");
                } catch (SQLException ex1) {
                    Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
            Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
          Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button3 = new java.awt.Button();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        button5.setLabel("GENERATE SLIP");
        button5.addActionListener(this::button5ActionPerformed);

        button6.setLabel("EXIT");
        button6.addActionListener(this::button6ActionPerformed);

        button3.setLabel("VIEW DETAILS");
        button3.addActionListener((ActionEvent evt) -> {
            try {
                Menuscm.this.button3ActionPerformed(evt);
            }catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        button1.setLabel("EMPLOYEE LIST");
        button1.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                button1ActionPerformed(evt);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        button2.setLabel("ADD EMPLOYEE");
        button2.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                button2ActionPerformed(evt);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Menuscm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

private void button5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         EmpSlip emp = new EmpSlip();
}                                       

private void button2ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {                                        
    // TODO add your handling code here:
    this.setVisible(false);
    AddEmp emp;
            emp = new AddEmp();
}

private void button1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {                                        
    // TODO add your handling code here:
    this.setVisible(false);
    EmpList emp;
            emp = new EmpList();
}

private void button3ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {                                        
    // TODO add your handling code here:
    this.setVisible(false);
    EmpDetail emp = new EmpDetail();
}                                       

private void button6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
// TODO add your handling code here:
 System.exit(0);
}                                       

private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
// TODO add your handling code here:
    
}                                 

private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
// TODO add your handling code here:
    
}                                  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Menuscm().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button5;
    private java.awt.Button button6;
    // End of variables declaration                   

        @Override
    public void setVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
 
